export type MethodAccess = 'public' | 'login-bootstrap' | 'auth-read' | 'write';

type AccessMap = Record<string, MethodAccess>;

function buildAccessMap(
  access: MethodAccess,
  names: readonly string[],
): AccessMap {
  return Object.fromEntries(names.map((name) => [name, access]));
}

export const METHOD_ACCESS: AccessMap = {
  ...buildAccessMap('public', [
    'album',
    'artist_album',
    'artist_detail',
    'artist_songs',
    'cloudsearch',
    'comment_album',
    'comment_music',
    'comment_mv',
    'comment_playlist',
    'comment_video',
    'lyric',
    'mv_detail',
    'mv_url',
    'playlist_catlist',
    'playlist_detail',
    'playlist_track_all',
    'related_allvideo',
    'simi_artist',
    'simi_playlist',
    'simi_song',
    'song_detail',
    'song_url_v1',
    'top_playlist',
    'top_playlist_highquality',
    'top_song',
    'toplist',
    'toplist_detail',
    'user_detail',
    'user_followeds',
    'user_follows',
    'user_playlist',
    'user_record',
  ]),
  ...buildAccessMap('login-bootstrap', [
    'login_qr_check',
    'login_qr_create',
    'login_qr_key',
  ]),
  ...buildAccessMap('auth-read', [
    'likelist',
    'personalized',
    'recommend_songs',
    'user_account',
    'user_subcount',
  ]),
  ...buildAccessMap('write', [
    'like',
    'playlist_create',
    'playlist_delete',
    'playlist_desc_update',
    'playlist_name_update',
    'playlist_order_update',
    'playlist_subscribe',
    'playlist_track_add',
    'playlist_track_delete',
  ]),
};

export const TOOL_ACCESS: AccessMap = {
  ...buildAccessMap('public', [
    'ncm_search',
    'ncm_song_detail',
    'ncm_song_url',
    'ncm_lyric',
    'ncm_album_detail',
    'ncm_artist_detail',
    'ncm_artist_songs',
    'ncm_artist_albums',
    'ncm_top_song',
    'ncm_mv_detail',
    'ncm_mv_url',
    'ncm_related_videos',
    'ncm_similar_songs',
    'ncm_similar_playlists',
    'ncm_similar_artists',
    'ncm_playlist_detail',
    'ncm_playlist_tracks',
    'ncm_playlist_categories',
    'ncm_top_playlist',
    'ncm_top_playlist_highquality',
    'ncm_toplist',
    'ncm_toplist_detail',
    'ncm_user_detail',
    'ncm_user_playlists',
    'ncm_user_follows',
    'ncm_user_followeds',
    'ncm_user_record',
    'ncm_comment_music',
    'ncm_comment_playlist',
    'ncm_comment_album',
    'ncm_comment_mv',
    'ncm_comment_video',
    'ncm_list_methods',
    'ncm_describe_method',
  ]),
  ...buildAccessMap('login-bootstrap', [
    'ncm_login_qr_check',
    'ncm_login_qr_start',
  ]),
  ...buildAccessMap('auth-read', [
    'ncm_liked_songs',
    'ncm_recommended_playlists',
    'ncm_recommended_songs',
    'ncm_user_account',
    'ncm_user_subcount',
  ]),
  ...buildAccessMap('write', [
    'ncm_like_song',
    'ncm_playlist_create',
    'ncm_playlist_delete',
    'ncm_playlist_name_update',
    'ncm_playlist_desc_update',
    'ncm_playlist_order_update',
    'ncm_playlist_subscribe',
    'ncm_playlist_track_add',
    'ncm_playlist_track_delete',
  ]),
};

export const SERVER_SESSION_METHODS = new Set([
  'song_url_v1',
  'likelist',
  'personalized',
  'recommend_songs',
  'user_account',
  'user_subcount',
  'like',
  'playlist_create',
  'playlist_delete',
  'playlist_desc_update',
  'playlist_name_update',
  'playlist_order_update',
  'playlist_subscribe',
  'playlist_track_add',
  'playlist_track_delete',
]);
